### ISSUE TITLE
Does not seem to work with current Foundry Version

### ISSUE THREAD

**Issue by cptn-cosmo** [smilligan93/max-crit-foundry-dnd5e#3]
I've attached the screenshot. Module is enabled, Foundry 0.5.7 DND5e 0.9

![image](https://user-images.githubusercontent.com/7382310/82700842-4b7ce280-9c6f-11ea-9452-fd72191777a4.png)

**Comment by cptn-cosmo** [comment]
Also I just noticed that I can't get the module settings to show for this module.

**Comment by smilligan93** [comment]
this has been updated for the latest version. Please let me know if you have any issues with it!
