### ISSUE TITLE
Cantrips not scaling

### ISSUE THREAD

**Issue by erpangilinan** [smilligan93/max-crit-foundry-dnd5e#7]
This module is preventing cantrip scaling in DnD5e 0.96

**Comment by erpangilinan** [comment]
Cantrip scaling was broken in base 0.95, so maybe whatever they hot fixed in the update is interfering with this module

**Comment by crymic** [comment]
> Cantrip scaling was broken in base 0.95, so maybe whatever they hot fixed in the update is interfering with this module

The 0.95 issue was due to a typo, of point[0] = point[0] the author forgot to reinclude in from 94 to 95. Which is why scaling is broken. However I think this is a different issue..

Spells with scaling enabled, won't even roll for damage with Max Crit module enabled.

**Comment by smilligan93** [comment]
Everything should be working in the newest version (0.1.6). Thank you for the reports!
